INSERT INTO CLIENTE (NOME) VALUES ('Apple Inc.');
INSERT INTO CLIENTE (NOME) VALUES ('Google');
INSERT INTO CLIENTE (NOME) VALUES ('Microsoft');
INSERT INTO CLIENTE (NOME) VALUES ('Tesla');
INSERT INTO CLIENTE (NOME) VALUES ('SpaceX');

INSERT INTO MODULO (NOME) VALUES ('Finaneiro');
INSERT INTO MODULO (NOME) VALUES ('Vendas');
INSERT INTO MODULO (NOME) VALUES ('Expedição');
INSERT INTO MODULO (NOME) VALUES ('Vendas');
INSERT INTO MODULO (NOME) VALUES ('Foguetes');

